version: '3.8'

services:
  media-server:
    build: .
    container_name: node_media_server
    ports:
      - "${RTMP_SERVER_PORT}:1935"  # RTMP
      - "${RTMP_HTTP_PORT}:8002"    # HTTP/WS for HLS/DASH
      - "${HTTP_PORT}:3006"         # Express web server
    volumes:
      - ./recordings:/app/recordings
      - ./snapshots:/app/snapshots
      - ./public:/app/public
    environment:
      - RTMP_HOST=${RTMP_HOST}
      - HTTP_PORT=${HTTP_PORT}
      - RTMP_SERVER_PORT=${RTMP_SERVER_PORT}
      - RTMP_HTTP_PORT=${RTMP_HTTP_PORT}
      - FFMPEG_PATH=${FFMPEG_PATH}
      - MAIN_BACKEND_SERVER_API_END_POINT=${FFMPEG_PATH}
      - MAIN_BACKEND_SERVER_API_KEY=${FFMPEG_PATH}
    restart: unless-stopped
