version: '3.8'

services:
  media-server:
    build: .
    container_name: node_media_server
    ports:
      - "1935:1935"         # RTMP
      - "8002:8002"         # HTTP/WS for HLS/DASH
      - "3006:3006"         # Express web server
    volumes:
      - ./recordings:/app/recordings
      - ./public:/app/public
    environment:
      - RTMP_HOST=localhost
      - HTTP_PORT=3006
      - RTMP_SERVER_PORT=1935
      - RTMP_HTTP_PORT=8002
      - FFMPEG_PATH=/usr/bin/ffmpeg
    restart: unless-stopped
